# Generated by Django 5.0 on 2025-04-18 04:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('requirements', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('architect_name', models.CharField(max_length=100)),
                ('architect_number', models.CharField(max_length=15)),
                ('source', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Indiamart', 'Indiamart'), ('Google', 'Google'), ('Reference', 'Reference'), ('Other', 'Other')], max_length=50)),
                ('source_other', models.CharField(blank=True, max_length=100, null=True)),
                ('enquiry_date', models.DateField()),
                ('customer_segment', models.CharField(choices=[('Retail/individual', 'Retail/individual'), ('B2B', 'B2B'), ('Reseller', 'Reseller'), ('Commercial/Corporate', 'Commercial/Corporate')], max_length=50)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('win_status', models.BooleanField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_leads', to=settings.AUTH_USER_MODEL)),
                ('follow_up_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_person', to=settings.AUTH_USER_MODEL)),
                ('sales_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_person', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, to='kushalapp.product')),
                ('services', models.ManyToManyField(blank=True, to='kushalapp.service')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup10_person', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup9_person', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup8_person', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup7_person', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup6_person', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup5_person', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup4_person', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup3_person', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowUp1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('Hot', 'Hot'), ('Warm', 'Warm'), ('Cold', 'Cold'), ('Not Interested', 'Not Interested')], max_length=20)),
                ('remarks', models.TextField()),
                ('close_status', models.CharField(blank=True, choices=[('Open', 'Open'), ('Win', 'Win'), ('Loss', 'Loss')], default='Open', max_length=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_visited', models.BooleanField()),
                ('inspection_done', models.BooleanField()),
                ('quotation_given', models.BooleanField()),
                ('quotation_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('quotation_file', models.FileField(blank=True, null=True, upload_to='quotations/')),
                ('next_followup_date', models.DateField(blank=True, null=True)),
                ('followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('next_followup_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup2_person', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
