# Generated by Django 5.0 on 2025-06-11 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0002_product_service_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('gst_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gst_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount_with_gst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kushalapp.lead')),
                ('products', models.ManyToManyField(blank=True, to='kushalapp.product')),
                ('services', models.ManyToManyField(blank=True, to='kushalapp.service')),
            ],
        ),
    ]
