# Generated by Django 5.0 on 2025-06-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0003_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
