# Generated by Django 5.0 on 2025-06-12 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0004_quotation_actual_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.quotation')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kushalapp.service')),
            ],
        ),
    ]
