# Generated by Django 5.0 on 2025-06-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0005_quotationproduct_quotationservice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='gst_percentage',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quantity',
        ),
    ]
