# Generated by Django 5.0 on 2025-06-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0007_quotation_actual_price_quotation_gst_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='actual_price',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='gst_percentage',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='quantity',
        ),
    ]
