# Generated by Django 5.0 on 2025-06-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0008_remove_quotation_actual_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='enable_gst',
            field=models.BooleanField(default=False),
        ),
    ]
