# Generated by Django 5.0 on 2025-06-16 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0010_invoiceterm_quotationterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='assigned_to_operations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
