# Generated by Django 5.0 on 2025-06-16 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0011_lead_assigned_to_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_to_operations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_operations_leads', to=settings.AUTH_USER_MODEL),
        ),
    ]
