# Generated by Django 5.0 on 2025-06-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0013_lead_customer_visited_lead_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='secondary_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
