# Generated by Django 5.0 on 2025-06-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0014_lead_secondary_mobile_number_alter_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='architect_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='architect_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
