# Generated by Django 5.0 on 2025-06-25 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0015_alter_lead_architect_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='mobile_number',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='lead',
            name='secondary_mobile_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
