# Generated by Django 5.0 on 2025-06-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0016_alter_lead_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
