# Generated by Django 5.0 on 2025-06-30 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0017_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup1',
            name='next_followup_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup2_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
