# Generated by Django 5.0 on 2025-06-30 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kushalapp', '0018_alter_followup1_next_followup_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='follow_up_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_person', to=settings.AUTH_USER_MODEL),
        ),
    ]
